controllers/PosterController.php
<?php
/**
 * Created by PhpStorm.
 * User: ganbarov_emin
 * Date: 07/03/15
 * Time: 02:53
 */

namespace app\controllers;

use app\models\Product;
use Yii;
use app\models\Cart;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;

class PosterController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $selected = new Product();

        return $this->render('index', [
            'selected' => $selected,
            'count'    => 1,
        ]);
    }

    /**
     * Добавляем плакат в корзину
     */
    public function actionAdd()
    {

        $cart = \Yii::$app->cart;

        if (isset($_GET['id'])) {
            $id = $_GET['id'];
            $selected = $cart->getPositionById($id);
        }

        $border = isset($_POST['border']) ? $_POST['border'] : false;
        $count = isset($_POST['count']) ? (int)$_POST['count'] : false;
        $cut = isset($_POST['cut']) ? $_POST['cut'] : false;

        if ($border !== false && $cut !== false){
            $model = Product::find()
                ->where([
                    'type'  => 1,
                    'color' => $border,
                    'cut'   => $cut,
                ])
                ->one();
            if ($count !== false && $model) {
                // удаляю, если это обновление
                if (isset($selected) && $selected) {
                    $cart->remove($selected);
                }
                $cart->put($model, $count);

                echo $count;
                exit;
            }

        }
        echo '0';
    }

    /**
     * Updates an existing Cart model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $selected = Yii::$app->cart->getPositionById($id);
        $selected = $selected ? $selected : new Product();

        return $this->render('index', [
            'selected'=>$selected,
            'count' => $selected->getQuantity()
        ]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Product;
use app\models\LoginForm;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\Cart;
use yii\web\NotFoundHttpException;
use app\models\Order;


class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionUpdateCart($id)
    {
        $position = \Yii::$app->cart->getPositionById($id);
        return $this->render('updateCart', [ 'position' => $position]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Страница с царями
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Страница со всеми правителями
     * @return string
     */
    public function actionGovernments()
    {
        return $this->render('governments');
    }

    public function actionMap()
    {
        return $this->render('map');
    }


}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<div id="overlay"></div>
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
    <div class="wrap container" id="<?= (Yii::$app->request->url == '/tzars/all') ? 'page_tzars_all' : ''; ?>">
        <?php
            $count = \Yii::$app->cart->getCount() ? \Yii::$app->cart->getCount() : '';
            $cart_class = 'empty';
            if ($count) {
                $cart_class = 'not_empty';
            }
        ?>
        <div class="row navigation">
            <div class="col-md-10">
                <a href=<?= Url::to(['site/map']); ?>  class="pull-right item_nav">
                    контакты
                </a>
                <a class="navbar-brand" id="main_logo" href="/">
                    <img src="/images/logo.png" width="180" id="<?= (Yii::$app->request->url == '/tzars/all') ? 'logo_page_tzars_all' : ''; ?>">
                </a>
                <a href=<?= Url::to(['t-shirt/index']); ?>  class="pull-right item_nav">
                    футболки
                </a>
                <a href=<?= Url::to(['poster/index']); ?>  class="pull-right item_nav" id="menu_caption_poster">
                    плакаты
                </a>
                <a href=<?= Url::to(['site/governments']); ?>  class="pull-right item_nav" id="menu_caption_tzars">
                    цари
                </a>
            </div>
            <div class="col-md-2">
                <span>
                    <a href="/cart/cart" class="pull-left item_nav cart_nav">
                        <span id="cart-img" class="<?= ($count > 0) ? 'full' : ''; ?>"></span>
                        <span id="radius-wrap" class="hide_on_empty <?=$cart_class?>">
                            <span id="cart-radius">&nbsp;</span>
                            <span id="cart_count" data-count="<?=(int)$count?>"><?=$count?></span>
                        </span>
                        &nbsp;
                    </a>
                </span>
            </div>
        </div>
        <!--  Содержимое view файла, который рендерится в контроллере -->
        <?= $content ?>
    </div>
<?php $this->endBody() ?>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter28364416 = new Ya.Metrika({id:28364416,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/28364416" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

</body>
</html>
<?php $this->endPage() ?>