models/Cart.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cart".
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $product_id
 * @property integer $count
 *
 * @property Order $order
 * @property Product $product
 */
class Cart extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cart';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_id', 'product_id', 'count'], 'required'],
            [['order_id', 'product_id', 'count'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_id' => 'Order ID',
            'product_id' => 'Product ID',
            'count' => 'Count',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrder()
    {
        return $this->hasOne(Order::className(), ['id' => 'order_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }

    /**
     * Получить описание с переносом на новую строку
     * @param   string   $description   Описание
     * @return string
     */
    public static function getDescription($description  = '')
    {
        $desc =  str_replace('.', '.<br>', $description);

        return $desc;
    }
}

controllers/CartController.php
<?php

namespace app\controllers;

use app\models\Product;
use Yii;
use app\models\Cart;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CartController implements the CRUD actions for Cart model.
 */
class CartController extends Controller
{

	public function behaviors()
	{
		return [
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}


	public function actionIndex()
	{
		// $selected = Product::find()->where(['available'=>1])
		//	 ->limit(1)->all();

		$selected = new Product;
		// $selected = Product::find()->one();
		// var_dump($selected->color);
		// $selected = $selected ? $selected[0] : new Product;


		$availibles = Product::getAvailibles($selected->cut, $selected->color, $selected->size);

		// var_dump($availibles);


		return $this->render('index', [
			'selected'=>$selected,
			'availibles' => $availibles,
			'count' => 1,
		]);
	}

	public function actionCart()
	{
		return $this->render('cart');
	}

	public function actionAdd()
	{

		$cart = \Yii::$app->cart;

		if (isset($_GET['id'])) {
			$id = $_GET['id'];
			$selected = $cart->getPositionById($id);
		}

		$color = isset($_POST['color']) ? $_POST['color'] : false;
		$cut = isset($_POST['cut']) ? $_POST['cut'] : false;
		$size = isset($_POST['size']) ? $_POST['size'] : false;
		$count = isset($_POST['count']) ? (int)$_POST['count'] : false;

		if ($color !== false && $cut !== false && $size !== false){
			$model = Product::find()
				->where([
					'color' => $color,
					'cut' => $cut,
					'size' => $size,
				])
				->one();
			if ($count !== false && $model) {
				// удаляю, если это обновление
				if (isset($selected) && $selected) {
					$cart->remove($selected);
				}
				$cart->put($model, $count);

				echo $count;
				exit;
			}

		}
		echo '0';
	}


	/**
	 * Displays a single Cart model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
		return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	 * Creates a new Cart model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new Cart();

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('create', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Updates an existing Cart model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{


		$selected = Yii::$app->cart->getPositionById($id);

		$selected = $selected ? $selected : new Product;


		$availibles = Product::getAvailibles(
			$selected->cut,
			$selected->color,
			$selected->size
		);

		return $this->render('index', [
			'selected'=>$selected,
			'availibles' => $availibles,
			'count' => $selected->getQuantity()
		]);
	}

	/**
	 * Deletes an existing Cart model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		$this->findModel($id)->delete();

		return $this->redirect('cart');
	}

	public function actionDeleteFromCart($id)
	{
		$position = \Yii::$app->cart->getPositionById($id);
		\Yii::$app->cart->remove($position);
		return $this->redirect('cart');
	}

	/**
	 * Finds the Cart model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return Cart the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = Cart::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}

	public function actionAvailibles()
	{
		$color = isset($_POST['color']) ? $_POST['color'] : false;
		$cut = isset($_POST['cut']) ? $_POST['cut'] : false;
		$size = isset($_POST['size']) ? $_POST['size'] : false;
		$count = isset($_POST['count']) ? $_POST['count'] : 0;


		$availibles = Product::getAvailibles($cut, $color, $size);

		$selected = new Product;

		// $view = new yii\web\View;
		echo $this->renderPartial('_palitra', [
			'selcut'=>$cut,
			'selcolor'=>$color,
			'selsize'=>$size,
			'count'=>$count,
			'selected'=>$selected,

			'availibles'=>$availibles
		]);

	}

}

controllers/OrderController.php
<?php

namespace app\controllers;

use app\models\Cart;
use Yii;
use app\models\Order;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
	public function behaviors()
	{
		return [
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}

	/**
	 * Lists all Order models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$dataProvider = new ActiveDataProvider([
			'query' => Order::find(),
		]);

		return $this->render('index', [
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Displays a single Order model.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionView($id)
	{
		return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	 * Creates a new Order model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new Order();

		if ($model->load(Yii::$app->request->post()) && $model->save()) {

			foreach ( \Yii::$app->cart->getPositions() as $position ) {
				$cart_model = new Cart();
				$cart_model->product_id = $position->id;
				$cart_model->order_id = $model->id;
				$cart_model->count = $position->getQuantity();
				$cart_model->save();
			}
			\Yii::$app->cart->removeAll();

			$model->sendHello();
			$model->sendAlarm();


			if ($model->mode_payment > 0) {
				return $this->renderPartial('yandex', ['order'=>$model]);
			} else {
				return $this->redirect(['success']);
			}
		} else {
			return $this->render('create', [
				'model' => $model,
			]);
		}
	}

	public function actionSuccess()
	{
		return $this->render('success');
	}

	// public function actionYandex($order_id)
	// {

	// 	$order = Order::findOne($order_id);
	// 	if (!$order) {
	// 		throw new NotFoundHttpException('The requested page does not exist.');
	// 	} else {
	// 		return $this->render('yandex', ['order'=>$order]);
	// 	}
	// }


	/**
	 * Updates an existing Order model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);

		if ($model->load(Yii::$app->request->post()) && $model->save()) {
			return $this->redirect(['view', 'id' => $model->id]);
		} else {
			return $this->render('update', [
				'model' => $model,
			]);
		}
	}

	/**
	 * Deletes an existing Order model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		$this->findModel($id)->delete();

		return $this->redirect(['index']);
	}

	/**
	 * Finds the Order model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return Order the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = Order::findOne($id)) !== null) {
			return $model;
		} else {
			throw new NotFoundHttpException('The requested page does not exist.');
		}
	}

	// public function actionTest()
	// {
	// 	return $this->renderPartial('yandex');
	// }
}

controllers/PosterController.php
<?php
/**
 * Created by PhpStorm.
 * User: ganbarov_emin
 * Date: 07/03/15
 * Time: 02:53
 */

namespace app\controllers;

use app\models\Product;
use Yii;
use app\models\Cart;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;

class PosterController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $selected = new Product();

        return $this->render('index', [
            'selected' => $selected,
            'count'    => 1,
        ]);
    }

    /**
     * Добавляем плакат в корзину
     */
    public function actionAdd()
    {

        $cart = \Yii::$app->cart;

        if (isset($_GET['id'])) {
            $id = $_GET['id'];
            $selected = $cart->getPositionById($id);
        }

        $border = isset($_POST['border']) ? $_POST['border'] : false;
        $count = isset($_POST['count']) ? (int)$_POST['count'] : false;
        $cut = isset($_POST['cut']) ? $_POST['cut'] : false;

        if ($border !== false && $cut !== false){
            $model = Product::find()
                ->where([
                    'type'  => 1,
                    'color' => $border,
                    'cut'   => $cut,
                ])
                ->one();
            if ($count !== false && $model) {
                // удаляю, если это обновление
                if (isset($selected) && $selected) {
                    $cart->remove($selected);
                }
                $cart->put($model, $count);

                echo $count;
                exit;
            }

        }
        echo '0';
    }

    /**
     * Updates an existing Cart model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $selected = Yii::$app->cart->getPositionById($id);
        $selected = $selected ? $selected : new Product();

        return $this->render('index', [
            'selected'=>$selected,
            'count' => $selected->getQuantity()
        ]);
    }
}

views/cart/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Cart */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cart-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'order_id')->textInput() ?>

    <?= $form->field($model, 'product_id')->textInput() ?>

    <?= $form->field($model, 'count')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/cart/_palitra.php
<?php
use app\models\Product;
?>
<div class="description_shirt">
    <p>
        <b>Футболка</b><br>
        History of Russia <br>
        100% хлопок <br>
        плотность 155 г/м
    </p>
    <div class="price_shirt">990.-</div>
</div>

<div class="cut">
        <?php foreach (Product::$cutsAvailable as $key => $cut):
            $disable_this = $availibles['cut'][$key] ? '' : 'disabled';
            $select_this = (string)$selcut === (string)$key && !$disable_this ? 'checked' : '';
        ?>
        <div>
            <div style="line-height: 30px;">
            <label class="wrap-checkbox <?= $select_this ?> <?=$disable_this?> cut-<?= $cut?>">
                <input id="cut-<?= $key?>"
                    name="cut"
                    class="checkbox"
                    <?= $disable_this?>
                    type="checkbox"
                    <?= $select_this ?>
                    value="<?=$key?>">
            </label>

            <span class="cut-label <?=$disable_this?>">
                <?= $cut ?>
            </span>
            </div>
        </div>
        <?php endforeach ?>
</div>

<div class="color">
    <p><b>цвет</b></p>
        <?php foreach (Product::$colorsAvailable as $key=>$color) {
            $disable_this = $availibles['color'][$key] ? '' : 'disabled';
            // var_dump($disable_this);
            $select_this = (string)$selcolor === (string)$key && !$disable_this ? 'checked' : '';
            if (in_array($key, [0,4])) {
                $close_on = $key+3;
                echo "<div class=''>";
            }
        ?>
        <label class="wrap-checkbox <?= $select_this ?> <?=$disable_this?> color-<?= $color?>">
            <input
                class="checkbox"
                id="color-<?= $color?>"
                name="color"
                <?= $disable_this ?>
                type="checkbox"
                <?= $select_this ?>
                value="<?=$key?>">
        </label>
        <?php
            if (in_array($key, [3,7])) {
                echo "</div>";
            }
        } ?>

    <br>

</div>


<div class="size">
    <p><b>размер</b></p>
    <?php
     foreach (Product::$sizesAvailable as $key=>$size) {
        $disable_this = $availibles['size'][$key] ? '' : 'disabled';

        if (in_array($key, [0,2,4,6,8])) {
            echo "<div class='size_row'>";
        }
        $select_this = (string)$selsize === (string)$key && !$disable_this  ? 'checked' : '';
        ?>

        <div class="size_cell" style="line-height: 30px;">
            <label class="wrap-checkbox <?= $select_this ?> <?=$disable_this?> size-<?= $size?>">
                <input id="size_<?=$key?>" class="checkbox" <?=$disable_this?> name="size" <?= $select_this ?> type="checkbox" value=<?=$key?>>
            </label>
            <span class="cut-label <?=$disable_this?>">
                <?=$size?>
            </span>
        </div>
        <?php
        if (in_array($key, [1,3,5,7,9])) {
            echo "</div>";
        }
    } ?>

</div>

<div class="number">
    <p><b>количество</b></p>
    <div class="count_row">
        <div class="btn count-btn btn-xs minus" type="button" value="&nbsp;-&nbsp;"><span class="icon_count_minus">-</span></div>
        <input id="count" class="number_count_products"  type="text" value="<?=$count?>" size="2">
        <div class="btn count-btn btn-xs plus" type="button" value="&nbsp;+&nbsp;">+</div>
    </div>
</div>

<br>
<?php $selected_id = $selected->id ? $selected->id : 0;?>
<input id="send_to_cart" data-selected_id="<?= $selected_id ?>" class="btn btn-block" type="button" value="добавить в корзину">

views/cart/cart.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\Product;
use app\models\Cart;

/* @var $this yii\web\View */
/* @var $model app\models\Cart */

?>

<div class=col-md-12 id="main_content_basket">
    <h2>Корзина</h2><br/><br/>
    <?php $cart = \Yii::$app->cart; if  (\Yii::$app->cart->getCount() > 0): ?>
        <div class="row">
            <div class="col-md-5 col-grey">
                <h4>Описание товара<h4>
            </div>
            <div class="col-md-4 col-grey">
                <h4>Детали<h4>
            </div>
            <div class="col-md-3 col-grey">
                <h4>Цена<h4>
            </div>
        </div>
        <?php foreach ( $cart->getPositions() as $position ) {?>
            <div class="row" style="padding: 5px; height: 145px;">
                <div class="right-border col-md-5">
                <div>
                    <div>
                        <?php if ($position->type == 0) { ?>
                            <img class = 'img-left' src="/images/small/<?php echo Product::$colorsAvailable[$position->color] ?>.jpg"/>
                        <?php } else { ?>
                            <img class = 'img-left' src="/images/posters/<?= Product::$posterColor[$position->color] ?>_border_02.jpg"/>
                        <?php } ?>
                        <?php echo Cart::getDescription($position->description); ?><br>
                    </div>
                </div>
                </div>
                <div class="right-border col-md-4">
                <p>
                    <?php if ($position->type == 0) { ?>
                        Цвет: <?php echo $position->getColorRu($position->color);?><br>
                        Крой: <?php echo Product::$cutsAvailable[$position->cut];?><br>
                        Размер: <?php echo Product::$sizesAvailable[$position->size];?><br>
                        Количество: <?php echo $position->getQuantity();?><br>
                        <?php echo Html::a('Изменить детали', ['cart/update', 'id' => $position->id], ['class' => 'btn-my btn-info-my'] ) ?>
                    <?php } else { ?>
                        Тип: <?= ($position->cut == 1) ? 'с рамкой' : 'без рамки'; ?><br/>
                        <?php
                            if ($position->cut == 1) {
                                echo 'Цвет: ' .  Product::$posterColorRus[$position->color] . '<br/>';
                            }
                        ?>
                        Количество: <?php echo $position->getQuantity();?><br>
                        <?php echo Html::a('Изменить детали', ['poster/update', 'id' => $position->id], ['class' => 'btn-my btn-info-my'] ) ?>
                    <?php } ?>
                </p>
                </div>
                <div class="col-md-3">
                    <?php echo $position->price; ?> руб
                </div>
            </div>
            <div class = "row ">
                <div class = "col-md-12">
                    <?php echo Html::a('Удалить', ['cart/delete-from-cart', 'id' => $position->id], ['class' => 'font-black']) ?>
                </div>
            </div>
            <hr >
        <?php }?>
        <div class="row">
            <div class="col-md-5">
            </div>
            <div class="col-md-4">
                <div> Итого </div>
            </div>
            <div class="col-md-3">
                <?php echo $cart->getCost().' руб' ?>
            </div>
        </div>
        <?php echo Html::a('КУПИТЬ', ['order/create', 'id' => $position->id], ['class' => 'btn-my btn-info-my-2 pull-right btn-level']) ?>
    <?php else: ?>
        Корзина пуста.
    <?php endif; ?>
</div>

views/cart/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Cart */

$this->title = 'Create Cart';
$this->params['breadcrumbs'][] = ['label' => 'Carts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cart-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cart/index.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Product;

//use yii\captcha\Captcha;
//use kartik\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Купить майку';
            // var_dump($availibles);

?>

<div class="row">
    <div class="col-md-9">
        <div class="t-short-image">
            <img id='t-short-image-big' class='image_big' src="/images/t-shirts/M_black.jpg"  />
        </div>
        <div class="subrow">
            <img id='t-short-image' class="subrow_img" src="/images/t-shirts/M_black.jpg"  />
            <img id='couple' class="subrow_img" src="/images/couple/M_black.jpg"/>
            <img id='close' class="subrow_img" src="/images/small/black.jpg"/>

        </div>
    </div>
    <div class="col-md-3">
        <div id='palitra' class="order-row">
                <?php echo $this->render('_palitra', [
                    'selcut'=>$selected->cut,
                    'selcolor'=>$selected->color,
                    'selsize'=>$selected->size,
                    'count'=>$count,
                    'selected'=>$selected,
                    'availibles'=>$availibles]);?>

        </div>

        <!-- для ошибки -->
        <div id="error" class="order-row"></div>

    </div>

</div>

views/cart/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Cart */

$this->title = 'Update Cart: ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Carts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="cart-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/cart/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Cart */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Carts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cart-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'order_id',
            'product_id',
            'count',
        ],
    ]) ?>

</div>